create table users(
id_u number generated by default as identity PRIMARY key,
username varchar2(100),
subscribers number
);

create table good(
id_g number generated by default as identity PRIMARY key,
goodname varchar2(100),
id_u references users(id_u),
price number,
description varchar2(1000)
);

create table tags(
id_t number generated by default as identity PRIMARY key,
nametag varchar2(50)
);

create table publication(
id_p number generated by default as identity PRIMARY key,
id_u references users(id_u),
title varchar2(100),
date_p date,
description varchar2(1000)
);

create table delivery(
id_d number generated by default as identity PRIMARY key,
namedev varchar2(50)
);

create table order_su(
id_o number generated by default as identity PRIMARY key,
id_d references delivery(id_d),
id_g references good(id_g),
date_o date,
seller number,
customer number
);


create table pub_tag(
id_p references publication(id_p),
id_t references tags(id_t)
);

with avg_price as(
select id_u,avg(price)
from good g
GROUP BY id_u)
select * from avg_price;



select * from users u
join good g on u.id_u=g.id_u;


create or replace procedure print_employee(x number) as
begin
    for c_emp in (select first_name, last_name from EMPLOYEES where EMPLOYEE_id=x)loop
        dbms_output.put_line(c_emp.first_name ||' '|| c_emp.last_name);
    end loop;
end;
begin
    print_employee(120);
end;

create or replace function get_department_avg_salary(x number) return number as
res number:=0;
n number:=0;
begin
    for c_emp in (select salary from EMPLOYEES where department_id=x)loop
        res:=res+c_emp.salary;
        n:=n+1;
    end loop;
    return res/n;
end;

select get_department_avg_salary(100) from DUAL;
